server:
  port: 8081  # Needed to specify which port your app runs on

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
      location: ${java.io.tmpdir}
  datasource:  # Required database connection details
    url: jdbc:postgresql:///XardHR
    username: XardHR
    password: XardHR
    driver-class-name: org.postgresql.Driver

  jpa:  # Basic JPA settings needed for database operations
    hibernate:
      ddl-auto: none  # We use 'none' because we're using Liquibase
    show-sql: true    # Helpful for development to see SQL queries
    properties:
      hibernate:
        format_sql: true

  liquibase:  # Required for Liquibase to work
    change-log: db/changelog/master.yaml
  # File storage configuration
  file:
    upload-dir: ./document-uploads

  # Enhanced logging configuration
  logging:
    level:
      org.banta.xardhr.service.document: DEBUG
      org.banta.xardhr.web.rest: DEBUG
    file:
      name: logs/xardhr.log

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000